apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
spec:
  template:
    spec:
      containers:
        - name: tic-tac-toe
          image: ghcr.io/radiantknightllc/devsecops-demo:staging-latest # Staging-specific image
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.75"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
