apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
spec:
  template:
    spec:
      containers:
        - name: tic-tac-toe
          image: ghcr.io/radiantknightllc/devsecops-demo:dev-latest # Dev-specific image
          imagePullPolicy: Always
